# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  pablo's tech blog 
#email: pablo@polvorin.com.ar
#description: > # this means to ignore newlines until "baseurl:"
#  pablo' tech blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.polvorin.com.ar" # the base hostname & protocol for your site
#twitter_username: polvorin
github_username:  polvorin

# Build settings
markdown: kramdown
